//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SplitTransactions.UpaySplitService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://upay.ucdavis.edu/upay/allocfeed", ConfigurationName="UpaySplitService.Alloc")]
    public interface Alloc {
        
        // CODEGEN: Generating message contract since the operation alloc is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        SplitTransactions.UpaySplitService.allocResponse alloc(SplitTransactions.UpaySplitService.allocRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://upay.ucdavis.edu/upay/allocfeed")]
    public partial class allocRequestTransaction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private allocRequestTransactionAllocation[] allocationField;
        
        private int merchantIdField;
        
        private string transactionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("allocation", Order=0)]
        public allocRequestTransactionAllocation[] allocation {
            get {
                return this.allocationField;
            }
            set {
                this.allocationField = value;
                this.RaisePropertyChanged("allocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int merchantId {
            get {
                return this.merchantIdField;
            }
            set {
                this.merchantIdField = value;
                this.RaisePropertyChanged("merchantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("transactionId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://upay.ucdavis.edu/upay/allocfeed")]
    public partial class allocRequestTransactionAllocation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fidField;
        
        private string chartField;
        
        private string accountField;
        
        private string subAccountField;
        
        private string projectField;
        
        private double amountField;
        
        private bool amountFieldSpecified;
        
        private double percentField;
        
        private bool percentFieldSpecified;
        
        private string giftNotificationIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fid {
            get {
                return this.fidField;
            }
            set {
                this.fidField = value;
                this.RaisePropertyChanged("fid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string chart {
            get {
                return this.chartField;
            }
            set {
                this.chartField = value;
                this.RaisePropertyChanged("chart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
                this.RaisePropertyChanged("account");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string subAccount {
            get {
                return this.subAccountField;
            }
            set {
                this.subAccountField = value;
                this.RaisePropertyChanged("subAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string project {
            get {
                return this.projectField;
            }
            set {
                this.projectField = value;
                this.RaisePropertyChanged("project");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
                this.RaisePropertyChanged("amountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double percent {
            get {
                return this.percentField;
            }
            set {
                this.percentField = value;
                this.RaisePropertyChanged("percent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool percentSpecified {
            get {
                return this.percentFieldSpecified;
            }
            set {
                this.percentFieldSpecified = value;
                this.RaisePropertyChanged("percentSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string giftNotificationId {
            get {
                return this.giftNotificationIdField;
            }
            set {
                this.giftNotificationIdField = value;
                this.RaisePropertyChanged("giftNotificationId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class allocRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="allocRequest", Namespace="https://upay.ucdavis.edu/upay/allocfeed", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("transaction", IsNullable=false)]
        public allocRequestTransaction[] allocRequest1;
        
        public allocRequest() {
        }
        
        public allocRequest(allocRequestTransaction[] allocRequest1) {
            this.allocRequest1 = allocRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class allocResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="allocResponse", Namespace="https://upay.ucdavis.edu/upay/allocfeed", Order=0)]
        public string allocResponse1;
        
        public allocResponse() {
        }
        
        public allocResponse(string allocResponse1) {
            this.allocResponse1 = allocResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface AllocChannel : SplitTransactions.UpaySplitService.Alloc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class AllocClient : System.ServiceModel.ClientBase<SplitTransactions.UpaySplitService.Alloc>, SplitTransactions.UpaySplitService.Alloc {
        
        public AllocClient() {
        }
        
        public AllocClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AllocClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AllocClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AllocClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SplitTransactions.UpaySplitService.allocResponse SplitTransactions.UpaySplitService.Alloc.alloc(SplitTransactions.UpaySplitService.allocRequest request) {
            return base.Channel.alloc(request);
        }
        
        public string alloc(allocRequestTransaction[] allocRequest1) {
            SplitTransactions.UpaySplitService.allocRequest inValue = new SplitTransactions.UpaySplitService.allocRequest();
            inValue.allocRequest1 = allocRequest1;
            SplitTransactions.UpaySplitService.allocResponse retVal = ((SplitTransactions.UpaySplitService.Alloc)(this)).alloc(inValue);
            return retVal.allocResponse1;
        }
    }
}
